version: "3"

services:

  memcached_01:
    image: memcached:alpine

  memcached_02:
    image: memcached:alpine

  memcached_03:
    image: memcached:alpine

  toxiproxy:
    image: shopify/toxiproxy:latest
    ports:
      - "8474:8474"
      - "11201:11201"
      - "11202:11202"
      - "11203:11203"
    volumes:
      - "./test/support/toxiproxy.json:/toxiproxy.json"
    command: ["-config", "/toxiproxy.json", "-host", "0.0.0.0"]
